# Generated by Django 4.2 on 2023-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
